const LS_KEY = "ledger_v1_local_data";
const SETTINGS_KEY = "ledger_v1_settings";
const CLOUD_TABLE = "ledger_user_data";

const monthNames = ["ינואר","פברואר","מרץ","אפריל","מאי","יוני","יולי","אוגוסט","ספטמבר","אוקטובר","נובמבר","דצמבר"];
const defaultCategories = ["בית","תחזוקת בית","רכבים","חסכונות","בריאות","תקשורת","כלבים","אוכל","דלק","מסעדות","בילויים","בגדים","עבודה","נופש","ביט","קרנות השוטרים","הטבות פיס","ארנק ממברס","אחר","קיזוז"];
const categoryRules = {
  "שופרסל":"אוכל", "רמי לוי":"אוכל", "סטופמרקט":"אוכל", "סופר":"אוכל", "מאפה":"אוכל", "קונטיינר":"אוכל", "סיטי מרקט":"אוכל",
  "ארומה":"מסעדות", "מקדונלד":"מסעדות", "פיצה":"מסעדות", "גפניקה":"מסעדות", "טאטי":"מסעדות", "wolt":"מסעדות",
  "דלק":"דלק", "פנגו":"רכבים", "חניון":"רכבים", "כביש 6":"רכבים", "דרך ארץ":"רכבים", "אקילס":"רכבים",
  "כללית":"בריאות", "הראל":"בריאות", "הפניקס":"בריאות", "מגדל":"בריאות", "סופרפארם":"בריאות",
  "apple":"תקשורת", "spotify":"תקשורת", "פרטנר":"תקשורת", "סלקום":"תקשורת", "airalo":"תקשורת",
  "אניפט":"כלבים", "וטרינר":"כלבים",
  "סינמה":"בילויים", "תיאטרון":"בילויים", "הטבות פיס":"הטבות פיס",
  "אל על":"נופש", "איסתא":"נופש", "מלון":"נופש", "amtrak":"נופש",
  "shein":"בגדים", "רנואר":"בגדים", "סטרדיווריוס":"בגדים",
  "מס הכנסה":"קיזוז", "ביטוח לאומי":"קיזוז", "מנורה":"קיזוז"
};

let supabaseClient = null;
let currentUser = null;

const today = new Date();
const state = {
  screen: "dashboard",
  year: today.getFullYear(),
  month: today.getMonth(),
  data: loadLocal() || { months: {}, categories: defaultCategories, importedFiles: [] }
};

function monthKey(y=state.year,m=state.month){ return `${y}-${String(m+1).padStart(2,"0")}`; }
function ensureMonth(){ const k=monthKey(); if(!state.data.months[k]) state.data.months[k]={ income:[], fixed:[], offsets:[], transactions:[] }; return state.data.months[k]; }
function fmt(n){ return Number(n||0).toLocaleString("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}); }
function uid(){ return crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random()); }
function esc(s){ return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c])); }
function toast(msg){ const host=document.getElementById("toastHost"); const el=document.createElement("div"); el.className="toast"; el.textContent=msg; host.appendChild(el); setTimeout(()=>el.remove(),2800); }

function loadLocal(){ try{return JSON.parse(localStorage.getItem(LS_KEY));}catch{return null;} }
async function saveAll(){ localStorage.setItem(LS_KEY, JSON.stringify(state.data)); document.getElementById("saveStatus").textContent="נשמר מקומית " + new Date().toLocaleTimeString("he-IL",{hour:"2-digit",minute:"2-digit"}); if(currentUser && supabaseClient){ await saveCloud(); } }
function loadSettings(){ const raw=localStorage.getItem(SETTINGS_KEY); const saved=raw?JSON.parse(raw):{}; return { url: saved.url || window.LEDGER_CONFIG.SUPABASE_URL || "", key: saved.key || window.LEDGER_CONFIG.SUPABASE_ANON_KEY || "" }; }
function saveSettings(url,key){ localStorage.setItem(SETTINGS_KEY, JSON.stringify({url,key})); }

async function initSupabase(){ const s=loadSettings(); if(!s.url || !s.key || !window.supabase){ updateCloudStatus("ענן: לא מוגדר"); return; } supabaseClient=window.supabase.createClient(s.url,s.key); const {data:{session}}=await supabaseClient.auth.getSession(); currentUser=session?.user||null; updateCloudStatus(currentUser?`ענן: מחובר (${currentUser.email})`:"ענן: מוגדר, לא מחובר"); if(currentUser) await loadCloud(); supabaseClient.auth.onAuthStateChange(async (_event,session)=>{ currentUser=session?.user||null; updateCloudStatus(currentUser?`ענן: מחובר (${currentUser.email})`:"ענן: לא מחובר"); if(currentUser) await loadCloud(); render(); }); }
function updateCloudStatus(text){ document.getElementById("cloudStatus").textContent=text; }
async function saveCloud(){ if(!currentUser) return; const payload={ user_id:currentUser.id, data:state.data, updated_at:new Date().toISOString() }; const {error}=await supabaseClient.from(CLOUD_TABLE).upsert(payload,{onConflict:"user_id"}); if(error){ console.error(error); toast("שגיאת שמירה בענן"); } else updateCloudStatus(`ענן: נשמר ${new Date().toLocaleTimeString("he-IL",{hour:"2-digit",minute:"2-digit"})}`); }
async function loadCloud(){ const {data,error}=await supabaseClient.from(CLOUD_TABLE).select("data").eq("user_id",currentUser.id).maybeSingle(); if(error){ console.error(error); toast("שגיאת טעינה מהענן"); return; } if(data?.data){ state.data=data.data; localStorage.setItem(LS_KEY, JSON.stringify(state.data)); toast("הנתונים נטענו מהענן"); } else await saveCloud(); }

function totals(){ const m=ensureMonth(); const income=m.income.reduce((s,x)=>s+Number(x.amount||0),0); const fixed=m.fixed.reduce((s,x)=>s+Number(x.amount||0),0); const offsets=m.offsets.reduce((s,x)=>s+Number(x.amount||0),0); const credit=m.transactions.filter(x=>Number(x.amount)>0).reduce((s,x)=>s+Number(x.amount||0),0); const expenses=fixed+credit-offsets; const balance=income-expenses; const review=m.transactions.filter(x=>x.needsReview).length; return {income,fixed,offsets,credit,expenses,balance,review,count:m.transactions.length}; }
function setScreen(screen){ state.screen=screen; document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.screen===screen)); render(); }
function render(){ document.getElementById("monthLabel").textContent=`${monthNames[state.month]} ${state.year}`; const titles={dashboard:["תמונת חודש","האם חסכת, לאן הלך הכסף ומה דורש טיפול"],transactions:["עסקאות","עריכה וסיווג של עסקאות החודש"],income:["הכנסות","משכורות והכנסות נוספות"],fixed:["הוצאות קבועות","משכנתא, הלוואות וכל חיוב קבוע"],offsets:["קיזוזים","מס, ביטוח לאומי, פנסיה וזיכויים"],categories:["קטגוריות","ניהול קטגוריות קבועות"],import:["ייבוא CSV","ייבוא עסקאות מקובצי אשראי"],backup:["גיבוי","ייצוא ושחזור נתונים"],settings:["הגדרות","חיבור Supabase וכניסה"]}; document.getElementById("screenTitle").textContent=titles[state.screen][0]; document.getElementById("screenSubtitle").textContent=titles[state.screen][1]; const c=document.getElementById("content"); c.innerHTML=({dashboard:renderDashboard,transactions:renderTransactions,income:()=>renderMoneyList("income","הכנסה חדשה"),fixed:()=>renderMoneyList("fixed","הוצאה קבועה חדשה"),offsets:()=>renderMoneyList("offsets","קיזוז חדש"),categories:renderCategories,import:renderImport,backup:renderBackup,settings:renderSettings}[state.screen])(); }
function renderDashboard(){ const t=totals(); const m=ensureMonth(); const byCat={}; m.transactions.forEach(x=>{ if(Number(x.amount)>0) byCat[x.category||"אחר"]=(byCat[x.category||"אחר"]||0)+Number(x.amount); }); const top=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,6); return `<section class="grid"><div class="card"><h3>הכנסות</h3><strong>${fmt(t.income)}</strong></div><div class="card"><h3>הוצאות</h3><strong>${fmt(t.expenses)}</strong></div><div class="card"><h3>עודף / גירעון</h3><strong class="${t.balance>=0?'good':'bad'}">${fmt(t.balance)}</strong></div><div class="card"><h3>דורש טיפול</h3><strong>${t.review}</strong></div></section><section class="panel"><h3>סיכום</h3><div class="row"><span class="pill">הוצאות קבועות: ${fmt(t.fixed)}</span><span class="pill">אשראי: ${fmt(t.credit)}</span><span class="pill">קיזוזים: ${fmt(t.offsets)}</span><span class="pill">עסקאות: ${t.count}</span></div></section><section class="panel"><h3>לאן הלך הכסף</h3>${top.length?top.map(([k,v])=>`<div class="row spaced"><span>${esc(k)}</span><strong>${fmt(v)}</strong></div>`).join(""):'<div class="empty">אין עדיין עסקאות.</div>'}</section><section class="panel"><h3>פעולה מהירה</h3><button class="btn primary" onclick="setScreen('import')">ייבוא קובץ CSV</button></section>`; }
function renderTransactions(){ const m=ensureMonth(); if(!m.transactions.length) return `<section class="panel"><div class="empty">אין עדיין עסקאות. עבור לייבוא CSV.</div></section>`; return `<section class="panel"><div class="row spaced"><h3>עסקאות</h3><button class="btn" onclick="downloadCsv()">ייצוא CSV</button></div><div class="table-wrap"><table class="table"><thead><tr><th>תאריך</th><th>ספק</th><th>סכום</th><th>כרטיס</th><th>קטגוריה</th><th>בן משפחה</th><th>הערה</th><th>בדיקה</th><th></th></tr></thead><tbody>${m.transactions.map(tx=>`<tr><td>${esc(tx.date)}</td><td>${esc(tx.merchant)}</td><td>${fmt(tx.amount)}</td><td>${esc(tx.card||"")}</td><td><select onchange="updateTx('${tx.id}','category',this.value)">${state.data.categories.map(c=>`<option ${c===(tx.category||"אחר")?'selected':''}>${esc(c)}</option>`).join("")}</select></td><td><select onchange="updateTx('${tx.id}','familyMember',this.value)">${["משפחה","פיני","מעין","יובל","ירדן","יואב"].map(p=>`<option ${p===(tx.familyMember||"משפחה")?'selected':''}>${p}</option>`).join("")}</select></td><td><input class="input" value="${esc(tx.note||"")}" onchange="updateTx('${tx.id}','note',this.value)"></td><td><input type="checkbox" ${tx.needsReview?'checked':''} onchange="updateTx('${tx.id}','needsReview',this.checked)"></td><td><button class="btn danger" onclick="deleteTx('${tx.id}')">מחק</button></td></tr>`).join("")}</tbody></table></div></section>`; }
function renderMoneyList(type,label){ const m=ensureMonth(); const items=m[type]; return `<section class="panel"><h3>${label}</h3><div class="form-grid"><input id="moneyName" class="input" placeholder="תיאור"><input id="moneyAmount" class="input" type="number" placeholder="סכום"><button class="btn primary" onclick="addMoney('${type}')">הוסף</button></div></section><section class="panel"><h3>רשימה</h3>${items.length?items.map(x=>`<div class="row spaced"><span>${esc(x.name)}</span><strong>${fmt(x.amount)}</strong><button class="btn danger" onclick="deleteMoney('${type}','${x.id}')">מחק</button></div>`).join(""):'<div class="empty">אין נתונים עדיין.</div>'}</section>`; }
function renderCategories(){ return `<section class="panel"><h3>קטגוריה חדשה</h3><div class="form-grid"><input id="catName" class="input" placeholder="שם קטגוריה"><button class="btn primary" onclick="addCategory()">הוסף</button></div></section><section class="panel"><h3>קטגוריות</h3>${state.data.categories.map(c=>`<div class="row spaced"><span>${esc(c)}</span><button class="btn danger" onclick="deleteCategory('${esc(c)}')">מחק</button></div>`).join("")}</section>`; }
function renderImport(){ return `<section class="panel"><h3>ייבוא CSV</h3><p class="muted">תומך בקבצי CSV פשוטים. שמות עמודות רצויים: date, merchant, amount, card. אפשר גם עברית: תאריך, שם בית עסק, סכום חיוב, כרטיס.</p><div id="drop" class="drop"><input id="csvFile" type="file" accept=".csv,text/csv" multiple><p>בחר קובץ CSV או גרור לכאן</p></div></section><section class="panel"><h3>PDF</h3><div class="empty">ייבוא PDF יתווסף בהמשך. כרגע נשתמש ב-CSV או הזנה ידנית.</div></section>`; }
function renderBackup(){ return `<section class="panel"><h3>גיבוי</h3><div class="row"><button class="btn primary" onclick="downloadBackup()">הורד גיבוי JSON</button><label class="btn ghost">שחזר מגיבוי<input type="file" accept=".json" style="display:none" onchange="restoreBackup(event)"></label></div></section>`; }
function renderSettings(){ const s=loadSettings(); return `<section class="panel"><h3>Supabase</h3><div class="stack"><input id="supabaseUrl" class="input" placeholder="Supabase URL" value="${esc(s.url)}"><input id="supabaseKey" class="input" placeholder="Supabase anon key" value="${esc(s.key)}"><button class="btn primary" onclick="saveSupabaseSettings()">שמור הגדרות</button></div></section><section class="panel"><h3>כניסה</h3><div class="stack"><input id="loginEmail" class="input" placeholder="האימייל שלך"><button class="btn primary" onclick="login()">שלח קישור כניסה</button><button class="btn ghost" onclick="logout()">התנתק</button></div><p class="muted">הנתונים נשמרים מקומית בכל מקרה. לאחר כניסה הם נשמרים גם בענן.</p></section>`; }

function addMoney(type){ const name=document.getElementById("moneyName").value.trim(); const amount=Number(document.getElementById("moneyAmount").value); if(!name||!amount) return toast("צריך תיאור וסכום"); ensureMonth()[type].push({id:uid(),name,amount}); saveAll(); render(); }
function deleteMoney(type,id){ ensureMonth()[type]=ensureMonth()[type].filter(x=>x.id!==id); saveAll(); render(); }
function addCategory(){ const n=document.getElementById("catName").value.trim(); if(!n) return; if(!state.data.categories.includes(n)) state.data.categories.push(n); saveAll(); render(); }
function deleteCategory(name){ if(name==="אחר") return toast("לא ניתן למחוק את אחר"); state.data.categories=state.data.categories.filter(c=>c!==name); Object.values(state.data.months).forEach(m=>m.transactions.forEach(t=>{if(t.category===name)t.category="אחר";})); saveAll(); render(); }
function updateTx(id,field,value){ const tx=ensureMonth().transactions.find(x=>x.id===id); if(tx){ tx[field]=value; saveAll(); if(field!=="note") render(); } }
function deleteTx(id){ ensureMonth().transactions=ensureMonth().transactions.filter(x=>x.id!==id); saveAll(); render(); }
function classify(merchant){ const low=String(merchant||"").toLowerCase(); for(const [k,v] of Object.entries(categoryRules)){ if(low.includes(k.toLowerCase())) return v; } return "אחר"; }
function parseCsv(text){ const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean); if(lines.length<2) return []; const delim=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?";":","; const split=line=>{ const out=[]; let cur="",q=false; for(const ch of line){ if(ch==='"') q=!q; else if(ch===delim&&!q){ out.push(cur.trim()); cur=""; } else cur+=ch; } out.push(cur.trim()); return out.map(x=>x.replace(/^"|"$/g,"")); }; const headers=split(lines[0]).map(h=>h.trim().toLowerCase()); const idx=(names)=>names.map(n=>headers.indexOf(n.toLowerCase())).find(i=>i>=0); const dateI=idx(["date","תאריך","תאריך רכישה"]); const merchantI=idx(["merchant","שם בית עסק","בית עסק","description","תיאור"]); const amountI=idx(["amount","סכום","סכום חיוב","חיוב"]); const cardI=idx(["card","כרטיס","מספר כרטיס"]); return lines.slice(1).map(line=>split(line)).map(cols=>{ const merchant=cols[merchantI]||""; const amount=Number(String(cols[amountI]||"0").replace(/[₪, ]/g,"").replace(/−/g,"-")); return {id:uid(),date:cols[dateI]||"",merchant,amount,card:cols[cardI]||"",category:classify(merchant),familyMember:"משפחה",note:"",needsReview:classify(merchant)==="אחר"}; }).filter(x=>x.merchant && !Number.isNaN(x.amount)); }
async function handleFiles(files){ let added=0, skipped=0; const m=ensureMonth(); for(const f of files){ const text=await f.text(); const rows=parseCsv(text); for(const r of rows){ const sig=`${r.date}|${r.merchant}|${r.amount}|${r.card}`; const exists=m.transactions.some(t=>`${t.date}|${t.merchant}|${t.amount}|${t.card}`===sig); if(exists){skipped++; continue;} r.sourceFile=f.name; m.transactions.push(r); added++; } } await saveAll(); toast(`נוספו ${added} עסקאות, דולגו ${skipped}`); setScreen("transactions"); }
function downloadBackup(){ const blob=new Blob([JSON.stringify(state.data,null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=`ledger-backup-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href); }
function restoreBackup(e){ const f=e.target.files[0]; if(!f) return; const reader=new FileReader(); reader.onload=async()=>{ try{state.data=JSON.parse(reader.result); await saveAll(); toast("הגיבוי שוחזר"); render();}catch{toast("קובץ גיבוי לא תקין");} }; reader.readAsText(f); }
function downloadCsv(){ const rows=ensureMonth().transactions; const csv=["date,merchant,amount,card,category,familyMember,note",...rows.map(r=>[r.date,r.merchant,r.amount,r.card,r.category,r.familyMember,r.note].map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(","))].join("\n"); const blob=new Blob([csv],{type:"text/csv"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=`ledger-transactions-${monthKey()}.csv`; a.click(); URL.revokeObjectURL(a.href); }
async function saveSupabaseSettings(){ saveSettings(document.getElementById("supabaseUrl").value.trim(),document.getElementById("supabaseKey").value.trim()); await initSupabase(); toast("הגדרות נשמרו"); render(); }
async function login(){ if(!supabaseClient) await initSupabase(); if(!supabaseClient) return toast("צריך להגדיר Supabase קודם"); const email=document.getElementById("loginEmail").value.trim(); if(!email) return toast("צריך אימייל"); const {error}=await supabaseClient.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}}); if(error) toast(error.message); else toast("נשלח קישור כניסה למייל"); }
async function logout(){ if(supabaseClient) await supabaseClient.auth.signOut(); currentUser=null; updateCloudStatus("ענן: לא מחובר"); render(); }

document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.screen)));
document.getElementById("prevMonth").addEventListener("click",()=>{ state.month--; if(state.month<0){state.month=11; state.year--;} render(); });
document.getElementById("nextMonth").addEventListener("click",()=>{ state.month++; if(state.month>11){state.month=0; state.year++;} render(); });
document.addEventListener("change",e=>{ if(e.target?.id==="csvFile") handleFiles(e.target.files); });
document.addEventListener("dragover",e=>{ const d=document.getElementById("drop"); if(d){e.preventDefault(); d.classList.add("drag");} });
document.addEventListener("dragleave",()=>document.getElementById("drop")?.classList.remove("drag"));
document.addEventListener("drop",e=>{ const d=document.getElementById("drop"); if(d){ e.preventDefault(); d.classList.remove("drag"); handleFiles(e.dataTransfer.files); }});

ensureMonth(); render(); initSupabase();
