
const APP_VERSION='v12';
const LS='ledger-v9-state'; const CFG='ledger-v9-config';
const months=['ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'];
const defaultCategories=['בית','תחזוקת בית','סופר','אוכל','מסעדות','בגדים','ילדים','חינוך','בריאות','רכב','דלק','ביטוח','תקשורת','נופש','בילויים','כלבים','עבודה','חסכונות','משכנתא','קיזוז','מסים','העברות','מתנות','יופי','פארמה','מחשבים','אחר'];
const exceptionTypes=['','חופשה בארץ','חופשה בחו"ל','בר/בת מצווה','אירוע משפחתי','שיפוץ','רכב חריג','ריהוט','ציוד לבית','בריאות חריגה','חינוך חריג','אחר'];
const catColors=['#2563eb','#0891b2','#059669','#65a30d','#ca8a04','#ea580c','#dc2626','#be185d','#9333ea','#4f46e5','#0f766e','#475569'];
const members=['משפחה','פיני','מעיין','יובל','ירדן','יואב'];
const memberColors={משפחה:'#334155',פיני:'#2563eb','מעיין':'#db2777','יובל':'#f59e0b','ירדן':'#10b981','יואב':'#8b5cf6'};
const defaultIncome=['משכורת פיני','משכורת מעיין','ביטוח לאומי ילדים'];
const defaultFixed=['משכנתא','חיסכון ילדים - מור','הלוואה קטנוע'];
const defaultOffsets=['מס הכנסה','ביטוח לאומי','ביטוח לאומי / מגדל','פנסיה מנורה'];
let state=loadState(); let config=loadConfig(); let supa=null; let cloudSession=false; let saveTimer=null;
const screens=[['dashboard','תמונת חודש'],['income','הכנסות'],['fixed','הוצאות קבועות'],['offsets','קיזוזים'],['transactions','פירוט עסקאות'],['categories','קטגוריות'],['import','ייבוא קבצים'],['backup','גיבוי ושחזור'],['cloud','גיבוי ענן'],['settings','הגדרות']];
let screen='dashboard';
function blank(){return {year:2026,month:6,income:[],fixed:[],offsets:[],transactions:[],categories:[],merchantRules:{},memberRules:{},exceptionRules:{},lastCloudAt:null}}
function loadState(){try{return ensureDefaults(JSON.parse(localStorage.getItem(LS))||blank())}catch{return ensureDefaults(blank())}}
function loadConfig(){try{return JSON.parse(localStorage.getItem(CFG))||{}}catch{return {}}}
function saveConfig(){localStorage.setItem(CFG,JSON.stringify(config))}
function ensureDefaults(s){s.categories=s.categories||[]; defaultCategories.forEach((n,i)=>{if(!s.categories.find(c=>c.name===n))s.categories.push({id:id(),name:n,color:catColors[i%catColors.length]})}); s.income=s.income||[]; defaultIncome.forEach(n=>{if(!s.income.find(x=>x.name===n))s.income.push({id:id(),name:n,amount:0})}); s.fixed=s.fixed||[]; defaultFixed.forEach(n=>{if(!s.fixed.find(x=>x.name===n))s.fixed.push({id:id(),name:n,amount:0,category:n.includes('משכנתא')?'משכנתא':'חסכונות'})}); s.offsets=s.offsets||[]; defaultOffsets.forEach(n=>{if(!s.offsets.find(x=>x.name===n))s.offsets.push({id:id(),name:n,amount:0,category:'קיזוז'})}); s.transactions=s.transactions||[]; s.merchantRules=s.merchantRules||{}; s.memberRules=s.memberRules||{}; s.exceptionRules=s.exceptionRules||{}; s.transactions.forEach(t=>{if(t.exceptional==null)t.exceptional=false; if(t.exceptionType==null)t.exceptionType=''; if(!t.members&&t.member)t.members=parseMembers(t.member)}); return s}
function persist(){state=ensureDefaults(state); localStorage.setItem(LS,JSON.stringify(state)); scheduleCloudSave(); render()}
function id(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function money(n){return Number(n||0).toLocaleString('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0})}
function byMonth(arr){return arr.filter(x=>(x.year??state.year)==state.year&&(x.month??state.month)==state.month)}
function totals(){const inc=state.income.reduce((a,b)=>a+num(b.amount),0); const fixed=state.fixed.reduce((a,b)=>a+num(b.amount),0); const off=state.offsets.reduce((a,b)=>a+num(b.amount),0); const tx=byMonth(state.transactions); const chargeable=tx.filter(t=>t.category!=='קיזוז'); const exceptionalTx=chargeable.filter(t=>!!t.exceptional); const regularTx=chargeable.filter(t=>!t.exceptional); const cardRegular=regularTx.reduce((a,b)=>a+num(b.amount),0); const cardExceptional=exceptionalTx.reduce((a,b)=>a+num(b.amount),0); const card=cardRegular+cardExceptional; const ignored=tx.filter(t=>t.category==='קיזוז').reduce((a,b)=>a+num(b.amount),0); const expensesRegular=fixed+cardRegular; const expenses=fixed+card; return {inc,fixed,off,card,cardRegular,cardExceptional,ignored,expensesRegular,expenses,balanceRegular:inc-expensesRegular+off,balance:inc-expenses+off,tx,regularTx,exceptionalTx,review:tx.filter(t=>t.review).length}}
function num(v){if(typeof v==='number')return v; return Number(String(v||'').replace(/,/g,'').replace(/[₪\s]/g,''))||0}
function cat(name){return state.categories.find(c=>c.name===name)||state.categories.find(c=>c.name==='אחר')}
function catOptions(sel){return state.categories.map(c=>`<option ${c.name===sel?'selected':''}>${esc(c.name)}</option>`).join('')}
function memOptions(sel){return members.map(m=>`<option ${m===sel?'selected':''}>${m}</option>`).join('')}
function exceptionTypeOptions(sel){return exceptionTypes.map(x=>`<option value="${esc(x)}" ${x===sel?'selected':''}>${x?esc(x):'לא חריג'}</option>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nav(){document.getElementById('nav').innerHTML=screens.map(([k,v])=>`<button class="${screen===k?'active':''}" onclick="go('${k}')">${v}</button>`).join('')}
function go(s){screen=s; render()}
function moveMonth(d){state.month+=d;if(state.month<0){state.month=11;state.year--}if(state.month>11){state.month=0;state.year++}persist()}
function render(){nav(); document.getElementById('monthLabel').textContent=months[state.month]+' '+state.year; const map={dashboard:['תמונת חודש','האם חסכת, לאן הלך הכסף ומה דורש טיפול'],income:['הכנסות','משכורות והכנסות נוספות'],fixed:['הוצאות קבועות','הוצאות שאינן אשראי'],offsets:['קיזוזים','סכומים שאינם צריכים להיחשב כהוצאה'],transactions:['פירוט עסקאות','שיוך לבני משפחה, קטגוריות והערות'],categories:['קטגוריות','ניהול צבעים וכללי סיווג'],import:['ייבוא קבצים','PDF חכם: ישראכרט, MAX וכאל'],backup:['גיבוי ושחזור','JSON מקומי'],cloud:['גיבוי ענן','שמירה דרך Netlify Function ל-Supabase'],settings:['הגדרות','הגדרות בסיסיות']}; document.getElementById('pageTitle').textContent=map[screen][0];document.getElementById('pageSub').textContent=map[screen][1]; updateCloudBadge(); document.getElementById('content').innerHTML=views[screen](); bindAfterRender()}
function updateCloudBadge(){const b=document.getElementById('cloudBadge'),s=document.getElementById('cloudSmall'); if(cloudSession){b.className='cloudBadge good'; b.firstChild.nodeValue='ענן: מחובר'; s.textContent='שמירה אוטומטית פעילה'} else {b.className='cloudBadge bad'; b.firstChild.nodeValue='ענן: לא מחובר'; s.textContent='שמירה מקומית פעילה'}}
const views={
 dashboard(){const t=totals(); const top=Object.entries(group(t.regularTx,'category')).sort((a,b)=>b[1]-a[1]).slice(0,8); const excByType=Object.entries(group(t.exceptionalTx,'exceptionType')).sort((a,b)=>b[1]-a[1]); const mem=Object.entries(groupMembers(t.tx.filter(x=>x.category!=='קיזוז'))).sort((a,b)=>b[1]-a[1]); const max=Math.max(1,...top.map(x=>x[1])); return `<div class="section"><div class="cards"><div class="card"><h3>הכנסות</h3><div class="big">${money(t.inc)}</div></div><div class="card"><h3>הוצאות רגילות</h3><div class="big">${money(t.expensesRegular)}</div><small>קבועות ${money(t.fixed)} · אשראי רגיל ${money(t.cardRegular)}</small></div><div class="card"><h3>הוצאות חריגות</h3><div class="big red">${money(t.cardExceptional)}</div><small>${t.exceptionalTx.length} עסקאות חריגות</small></div><div class="card"><h3>מאזן רגיל / כולל</h3><div class="big ${t.balanceRegular>=0?'green':'red'}">${money(t.balanceRegular)}</div><small>כולל חריגות: <b class="${t.balance>=0?'green':'red'}">${money(t.balance)}</b></small></div></div><div class="cards"><div class="card"><h3>סה"כ הוצאות</h3><div class="big">${money(t.expenses)}</div><small>רגילות + חריגות</small></div><div class="card"><h3>קיזוזים</h3><div class="big">${money(t.off)}</div></div><div class="card"><h3>דורש בדיקה</h3><div class="big">${t.review}</div><small>עסקאות: ${t.tx.length}</small></div><div class="card"><h3>עסקאות חריגות</h3><div class="big">${t.exceptionalTx.length}</div><small>ניתן לשנות בכל שורה</small></div></div><div class="grid2"><div class="panel"><h3>לאן הלך הכסף - ללא חריגות</h3><div class="summaryList">${top.length?top.map(([k,v])=>`<div><b>${esc(k||'אחר')}</b> <span>${money(v)}</span><div class="bar"><span style="width:${Math.round(v/max*100)}%"></span></div></div>`).join(''):'<div class="hint">אין עסקאות רגילות עדיין.</div>'}</div></div><div class="panel"><h3>הוצאות חריגות לפי סוג</h3><div class="summaryList">${excByType.length?excByType.map(([k,v])=>`<div><b>${esc(k||'חריג - אחר')}</b> ${money(v)}</div>`).join(''):'<div class="hint">אין הוצאות חריגות החודש.</div>'}</div></div></div><div class="panel"><h3>בני משפחה</h3><div class="summaryList">${mem.length?mem.map(([k,v])=>`<div><span class="memdot" style="background:${memberColors[k]||'#64748b'}"></span> <b>${esc(k)}</b> ${money(v)}</div>`).join(''):'<div class="hint">אין נתונים עדיין.</div>'}</div></div></div>`},
  income(){return listMoney('income','הכנסה','שם הכנסה')}, fixed(){return listMoney('fixed','הוצאה קבועה','שם הוצאה')}, offsets(){return listMoney('offsets','קיזוז','שם קיזוז')},
 transactions(){const tx=byMonth(state.transactions).sort(sortTx); return `<div class="panel"><div class="toolbar"><button class="btn primary" onclick="addTx()">הוסף עסקה</button><button class="btn red" onclick="clearImportedMonth()">מחק יבוא חודש נוכחי</button><input id="q" placeholder="חיפוש לפי ספק, כרטיס, הערה..." oninput="filterTx()" style="max-width:360px"><select id="fcard" onchange="filterTx()"><option value="">כל הכרטיסים</option>${cardOptions()}</select><select id="fcat" onchange="filterTx()"><option value="">כל הקטגוריות</option>${catOptions('')}</select><select id="fmem" onchange="filterTx()"><option value="">כל בני המשפחה</option>${memOptions('')}</select><select id="fexc" onchange="filterTx()"><option value="">רגיל וחריג</option><option value="regular">רגילות בלבד</option><option value="exceptional">חריגות בלבד</option></select></div><div class="hint" style="margin-bottom:12px">העסקאות מסודרות לפי מספר כרטיס ואז לפי תאריך. שינוי קטגוריה, בני משפחה או חריגה נשמר ככלל לספק ויחול אוטומטית בפעם הבאה.</div><div class="tablewrap"><div class="row wide head txrow"><div>תאריך</div><div>כרטיס</div><div>ספק</div><div>סכום</div><div>קטגוריה</div><div>בני משפחה</div><div>תשלומים</div><div>חריגה</div><div></div></div><div id="txbody">${tx.map(txRow).join('')}</div></div></div>`},
  categories(){return `<div class="panel"><div class="input2"><input id="newcat" placeholder="קטגוריה חדשה"><input id="newcatcolor" type="color" value="#2563eb"><button class="btn primary" onclick="addCat()">הוסף</button></div>${state.categories.map(c=>`<div class="row"><input value="${esc(c.name)}" onchange="updCat('${c.id}','name',this.value)"><input type="color" value="${c.color}" onchange="updCat('${c.id}','color',this.value)"><span class="colorTag" style="background:${c.color}">${esc(c.name)}</span><button class="btn red" onclick="delCat('${c.id}')">מחק</button></div>`).join('')}</div>`},
 import(){return `<div class="panel"><h3>ייבוא CSV / PDF חכם</h3><div class="drop"><p>בחר קבצי ישראכרט, MAX, כאל או CSV. המערכת תזהה ספק, סכום, כרטיס, קטגוריה ובני משפחה לפי כללים שנלמדו.</p><button class="btn primary" onclick="fileInput.click()">בחר קבצים</button></div><div class="warn" style="margin-top:14px">לפני שמירה סופית, בדוק במסך פירוט עסקאות את השורות החדשות. שינוי קטגוריה או שיוך לבני משפחה יישמר ככלל לפעמים הבאות.</div><pre class="log" id="importLog"></pre></div>`},
 backup(){return `<div class="grid2"><div class="panel"><h3>גיבוי JSON</h3><button class="btn primary" onclick="downloadBackup()">הורד גיבוי JSON</button></div><div class="panel"><h3>שחזור JSON</h3><button class="btn amber" onclick="restoreInput.click()">שחזר מקובץ</button></div></div>`},
 cloud(){return `<div class="panel cloud"><h3>גיבוי ענן - שרת Netlify</h3><div class="hint">גרסה זו לא שולחת את הדפדפן ישירות ל-Supabase. האתר קורא ל-Netlify Function, והשרת שומר את הנתונים ב-Supabase. אין מיילים, אין Redirect, ואין Anon Key בתוך האתר.</div><div class="row" style="grid-template-columns:1fr 1fr auto auto;margin-top:14px"><input id="cEmail" placeholder="Email" value="${esc(config.email||'')}"><input id="cPass" placeholder="סיסמת Ledger" value="${esc(config.password||'')}" type="password"><button class="btn primary" onclick="saveCloudConfig()">שמור</button><button class="btn" onclick="testCloud()">בדיקת שרת</button></div><div class="toolbar"><button class="btn primary" onclick="signIn()">טען מהענן / כניסה</button><button class="btn primary" onclick="saveCloudNow()">שמור לענן עכשיו</button><button class="btn" onclick="cloudSnapshot()">צור Snapshot</button><button class="btn red" onclick="signOut()">התנתק</button></div><div class="warn">סטטוס: ${cloudSession?'מחובר':'לא מחובר'}${state.lastCloudAt?' · נשמר לאחרונה: '+state.lastCloudAt:''}</div><pre class="log" id="log"></pre></div>`},
 settings(){return `<div class="panel"><h3>הגדרות</h3><div class="hint">הכתובת הקבועה המומלצת: https://pini-ledger.netlify.app. עדכוני גרסה צריכים לעלות לאותה כתובת.</div></div>`}
};
function listMoney(type,label,ph){return `<div class="panel"><div class="input2"><input id="n_${type}" placeholder="${ph}"><input id="a_${type}" type="number" placeholder="סכום"><button class="btn primary" onclick="addMoney('${type}')">הוסף ${label}</button></div>${state[type].map(x=>`<div class="row"><input value="${esc(x.name)}" onchange="updMoney('${type}','${x.id}','name',this.value)"><input type="number" value="${esc(x.amount)}" onchange="updMoney('${type}','${x.id}','amount',this.value)"><select onchange="updMoney('${type}','${x.id}','category',this.value)">${catOptions(x.category|| (type==='offsets'?'קיזוז':'אחר'))}</select><button class="btn red" onclick="delMoney('${type}','${x.id}')">מחק</button></div>`).join('')}</div>`}
function group(arr,key){return arr.reduce((a,x)=>{const k=x[key]||'אחר'; a[k]=(a[k]||0)+num(x.amount); return a},{})}
function groupMembers(arr){return arr.reduce((a,t)=>{const ms=t.members&&t.members.length?t.members:parseMembers(t.member||'משפחה'); ms.forEach(m=>{a[m.member]=(a[m.member]||0)+num(t.amount)*(num(m.percent)/100)}); return a},{})}
function bindAfterRender(){fileInput.onchange=importFiles; restoreInput.onchange=restoreBackup}
function addMoney(t){const n=document.getElementById('n_'+t).value.trim(), a=num(document.getElementById('a_'+t).value); if(!n)return; state[t].push({id:id(),name:n,amount:a,category:t==='offsets'?'קיזוז':'אחר'}); persist()}
function updMoney(t,i,k,v){const x=state[t].find(y=>y.id===i); if(x){x[k]=k==='amount'?num(v):v; persist()}}
function delMoney(t,i){state[t]=state[t].filter(x=>x.id!==i); persist()}
function cardOptions(){return [...new Set(byMonth(state.transactions).map(x=>x.card).filter(Boolean))].sort().map(c=>`<option>${esc(c)}</option>`).join('')}
function sortTx(a,b){return String(a.card||'').localeCompare(String(b.card||''),'he')||String(a.date||'').localeCompare(String(b.date||''))||String(a.merchant||'').localeCompare(String(b.merchant||''),'he')}
function txRow(t){const c=cat(t.category); const split=memberText(t); const exc=t.exceptional?'exceptional':'regular'; const source=t.sourceCategory&&t.sourceCategory!==t.category?`<span class="sourceCat">מקור: ${esc(t.sourceCategory)}</span>`:''; return `<div class="row wide txrow ${t.exceptional?'exceptionalRow':''}" data-card="${esc(t.card||'')}" data-search="${esc(Object.values(t).join(' ').toLowerCase())}" data-cat="${esc(t.category)}" data-mem="${esc(split)}" data-exc="${exc}"><input type="date" value="${esc(t.date)}" onchange="updTx('${t.id}','date',this.value)"><div class="cardTag">${esc(t.card||'')}</div><div><input class="merchantCell" value="${esc(t.merchant)}" onchange="updTx('${t.id}','merchant',this.value,true,true,true)">${source}${t.note?`<div class="compactNote" title="${esc(t.note)}">${esc(t.note)}</div>`:''}</div><input class="amountCell" type="number" value="${esc(t.amount)}" onchange="updTx('${t.id}','amount',this.value)"><select style="border-right:8px solid ${c.color}" onchange="updTx('${t.id}','category',this.value,true)">${catOptions(t.category)}</select><div class="memberChips">${memberChips(t)}</div><input class="installment" value="${esc(t.installment||'')}" placeholder="תשלום" onchange="updTx('${t.id}','installment',this.value)"><div><label class="pill"><input type="checkbox" ${t.exceptional?'checked':''} onchange="updTx('${t.id}','exceptional',this.checked,false,false,true)"> חריגה</label><select onchange="updTx('${t.id}','exceptionType',this.value,false,false,true)" ${t.exceptional?'':'disabled'}>${exceptionTypeOptions(t.exceptionType||'')}</select></div><button class="btn red" onclick="delTx('${t.id}')">מחק</button></div>`}
function memberChips(t){const selected=new Set((t.members&&t.members.length?t.members:parseMembers(t.member||'משפחה')).map(x=>x.member)); return members.map(m=>`<label class="mchip ${selected.has(m)?'on':''}" title="לחץ כדי לשייך או להסיר"><input type="checkbox" ${selected.has(m)?'checked':''} onchange="toggleTxMember('${t.id}','${m}',this.checked)">${esc(m)}</label>`).join('')}
function toggleTxMember(i,m,on){const t=state.transactions.find(x=>x.id===i); if(!t)return; let cur=(t.members&&t.members.length?t.members:parseMembers(t.member||'משפחה')).map(x=>x.member).filter(Boolean); if(m==='משפחה'){cur=on?['משפחה']:[]} else {cur=cur.filter(x=>x!=='משפחה'); if(on&&!cur.includes(m))cur.push(m); if(!on)cur=cur.filter(x=>x!==m)} if(!cur.length)cur=['משפחה']; t.members=parseMembers(cur.join(', ')); t.member=memberText(t); if(t.merchant)learnMerchant(t); persist()}
function addTx(){state.transactions.push({id:id(),year:state.year,month:state.month,date:new Date().toISOString().slice(0,10),merchant:'',amount:0,card:'',category:'אחר',member:'משפחה',members:parseMembers('משפחה'),note:'',review:false,exceptional:false,exceptionType:'',installment:'',source:'manual'}); persist(); go('transactions')}
function updTx(i,k,v,learnCat=false,learnMem=false,learnExc=false){const t=state.transactions.find(x=>x.id===i); if(!t)return; if(k==='amount')t[k]=num(v); else if(k==='membersText'){t.members=parseMembers(v); t.member=memberText(t)} else if(k==='exceptional'){t.exceptional=!!v; if(!t.exceptional)t.exceptionType=''} else t[k]=v; if(t.exceptional && !t.exceptionType)t.exceptionType='אחר'; if((learnCat||learnMem||learnExc)&&t.merchant)learnMerchant(t); persist()}
function delTx(i){state.transactions=state.transactions.filter(x=>x.id!==i); persist()}
function clearImportedMonth(){if(!confirm('למחוק את כל העסקאות שיובאו בחודש הנוכחי? נתוני הכנסות/קבועות/קיזוזים לא יימחקו.'))return; state.transactions=state.transactions.filter(t=>!((t.year??state.year)==state.year&&(t.month??state.month)==state.month&&(t.source||t.note||'').toLowerCase().includes('pdf'))); persist()}
function filterTx(){const q=(document.getElementById('q')?.value||'').toLowerCase(), fcard=document.getElementById('fcard')?.value||'', fc=document.getElementById('fcat')?.value||'', fm=document.getElementById('fmem')?.value||'', fe=document.getElementById('fexc')?.value||''; document.querySelectorAll('#txbody .txrow').forEach(r=>{const ok=(!q||r.dataset.search.includes(q))&&(!fcard||r.dataset.card===fcard)&&(!fc||r.dataset.cat===fc)&&(!fm||r.dataset.mem.includes(fm))&&(!fe||r.dataset.exc===fe); r.style.display=ok?'grid':'none'})}
function addCat(){const n=document.getElementById('newcat').value.trim(); if(!n)return; if(!state.categories.find(c=>c.name===n))state.categories.push({id:id(),name:n,color:document.getElementById('newcatcolor').value}); persist()}
function updCat(i,k,v){const c=state.categories.find(x=>x.id===i); if(c){const old=c.name;c[k]=v;if(k==='name'){state.transactions.forEach(t=>{if(t.category===old)t.category=v})} persist()}}
function delCat(i){const c=state.categories.find(x=>x.id===i); if(!c)return; state.categories=state.categories.filter(x=>x.id!==i); state.transactions.forEach(t=>{if(t.category===c.name)t.category='אחר'}); persist()}
function clean(s){return String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim()}
function ruleFor(m){const x=clean(m); const r=state.merchantRules[x]; if(!r)return null; if(typeof r==='string')return {category:r}; return r}
function learnMerchant(t){const x=clean(t.merchant); if(!x)return; state.merchantRules[x]={category:t.category||'אחר',members:t.members||parseMembers(t.member||'משפחה'),exceptional:!!t.exceptional,exceptionType:t.exceptionType||''}; state.memberRules[x]=memberText(t); state.exceptionRules[x]={exceptional:!!t.exceptional,exceptionType:t.exceptionType||''}}
function guessCat(m, sourceCat=''){const x=clean(m+' '+sourceCat); const r=ruleFor(m); if(r&&r.category)return r.category;
  if(/מס הכנסה|ביטוח לאומי|מגדל|מנורה|פנסיה/.test(x))return 'קיזוז';
  if(/שופרסל|רמי לוי|ויקטורי|יוחננוף|קרפור|חצי חינם|סופר|מכולת|market|carrefour/.test(x))return 'סופר';
  if(/פז|דלק|סונול|דור אלון|פנגו|מוביט|חניון|כביש|דרך ארץ|gett|uber|שירותי רכב|מוסך/.test(x))return 'רכב';
  if(/ביטוח|הראל|מגדל|הפניקס|כללית|בריאות|סיעוד|רפוא|ביקורופא/.test(x))return 'בריאות';
  if(/מסעד|קפה|פיצה|המבורגר|סושי|גלידה|wolt|tatti|mamma|burger|food|מאפה|מעדניות/.test(x))return 'מסעדות';
  if(/סלקום|פרטנר|בזק|הוט|חשמל|מים|ארנונה|תקשורת/.test(x))return 'תקשורת';
  if(/shein|zara|h&m|קסטרו|פוקס|אורבניקה|הלבשה|decathlon|דקאתלון/.test(x))return 'בגדים';
  if(/בית ספר|בתי ספר|צופים|שבט|אפטר סקול|חינוך|קהילה|חוג|ספורט בגין/.test(x))return 'ילדים';
  if(/paybox|bit|העברת כספים|ארנק|טעינת כרטיס/.test(x))return 'העברות';
  if(/נופש|טיסה|airalo|מלון|hotel|אל על|איסתא|travel|paris|krakow|warszawa/.test(x))return 'נופש';
  if(/סופרפארם|פארם|pharm/.test(x))return 'פארמה';
  if(/apple|spotify|google|amazon|מחשבים|באג|חשמל|אלקטרה|מחסני חשמל/.test(x))return 'מחשבים';
  if(/יופי|קוסמטיקה|sephora|kiko/.test(x))return 'יופי';
  return sourceCat && state.categories.find(c=>c.name===sourceCat) ? sourceCat : 'אחר'}
function guessExceptional(m, catName=''){const r=ruleFor(m); if(r&&typeof r.exceptional==='boolean')return !!r.exceptional; const x=clean(m+' '+catName); if(/אל על|airalo|hotel|מלון|איסתא|travel|נופש|טיסה|paris|krakow|warszawa|kandersteg|mouches|bateaux|ובר מאמא|mamma|lego store paris/.test(x))return true; if(/בר מצווה|בת מצווה|אירוע|אולם|שיפוץ|ריהוט|עמינח|טסט|מוסך חריג/.test(x))return true; return false}
function guessExceptionType(m, catName=''){const r=ruleFor(m); if(r&&r.exceptionType)return r.exceptionType; const x=clean(m+' '+catName); if(/בר מצווה|בת מצווה/.test(x))return 'בר/בת מצווה'; if(/אל על|airalo|hotel|מלון|איסתא|travel|טיסה|paris|krakow|warszawa|kandersteg|mouches|bateaux|mamma|lego store paris/.test(x))return 'חופשה בחו"ל'; if(/שיפוץ/.test(x))return 'שיפוץ'; if(/עמינח|ריהוט/.test(x))return 'ריהוט'; if(/בריאות חריגה/.test(x))return 'בריאות חריגה'; return 'אחר'}
function guessMembers(m){const r=ruleFor(m); if(r&&r.members)return r.members; const txt=state.memberRules[clean(m)]||'משפחה'; return parseMembers(txt)}
function guessMem(m){return memberText({members:guessMembers(m),member:'משפחה'})}
function parseMembers(text){let raw=String(text||'משפחה').split(',').map(x=>x.trim()).filter(Boolean); if(!raw.length)raw=['משפחה']; const out=raw.map(x=>{let [name,p]=x.split(':').map(y=>y.trim()); if(!members.includes(name))name=name||'משפחה'; return {member:name,percent:p?num(p):null}}); const missing=out.filter(x=>x.percent==null); const used=out.reduce((a,x)=>a+(x.percent||0),0); const rest=Math.max(0,100-used); missing.forEach(x=>x.percent=missing.length?rest/missing.length:0); const sum=out.reduce((a,x)=>a+x.percent,0)||100; out.forEach(x=>x.percent=Math.round((x.percent/sum)*1000)/10); return out}
function memberText(t){const arr=t.members&&t.members.length?t.members:(t.member?[{member:t.member,percent:100}]:[{member:'משפחה',percent:100}]); if(arr.length===1)return arr[0].member; return arr.map(x=>`${x.member}:${x.percent}`).join(', ')}
function memberColorFor(text){const first=String(text||'משפחה').split(/[,:]/)[0].trim(); return memberColors[first]||'#64748b'}
function dupKey(t){return [t.card,t.date,clean(t.merchant),num(t.amount).toFixed(2)].join('|')}
function importLog(s){const el=document.getElementById('importLog'); if(el)el.textContent += s+'\n'}
async function importFiles(e){const files=[...e.target.files]; let total=0; for(const f of files){try{let text=''; if(f.name.toLowerCase().endsWith('.pdf')) text=await extractPdfText(f); else text=await f.text(); const added=parseText(text,f.name); total+=added; importLog(`${f.name}: יובאו ${added} עסקאות`)}catch(err){importLog(`${f.name}: שגיאה ${err.message||err}`); alert(`${f.name}: ${err.message||err}`)}} e.target.value=''; persist(); alert(`סה״כ יובאו ${total} עסקאות`); go('transactions')}
async function extractPdfText(file){if(!window.pdfjsLib)throw new Error('pdf.js לא נטען. נסה רענון מלא Ctrl+F5'); pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; const buf=await file.arrayBuffer(); const pdf=await pdfjsLib.getDocument({data:buf}).promise; let all=''; for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p); const tc=await page.getTextContent(); const items=tc.items.map(it=>it.str); all += items.join('\n')+'\n'} return all}
function parseText(text,file){let added=0; const existing=new Set(state.transactions.map(dupKey)); const card=detectCard(text,file); let txs=[]; if(/MAX|עסקאות במועד החיוב|max פירוט/i.test(text)||/max|5213|5015/i.test(file))txs=parseMax(text,file,card); else if(/Cal\.|כאל|פירוט עסקאות וחיובים לכרטיס|digital-web\.cal/i.test(text)||/cal|3558|0591|1570|4880/i.test(file))txs=parseCal(text,file,card); else if(/ישראכרט|עסקות שחויבו|רכישות בחו"ל|isracard/i.test(text)||/isracard|0016|6020|7398|7938/i.test(file))txs=parseIsracard(text,file,card); else txs=parseGeneric(text,file,card); txs.forEach(tx=>{tx.id=id(); tx.year=state.year; tx.month=state.month; tx.card=tx.card||card; tx.category=guessCat(tx.merchant,tx.sourceCategory||''); tx.members=guessMembers(tx.merchant); tx.member=memberText(tx); tx.exceptional=guessExceptional(tx.merchant,tx.category); tx.exceptionType=tx.exceptional?guessExceptionType(tx.merchant,tx.category):''; tx.note=tx.note||''; tx.source=tx.source||'pdf'; tx.review=tx.category==='אחר' || !tx.merchant; const k=dupKey(tx); if(!existing.has(k)&&tx.date&&tx.merchant&&Number.isFinite(num(tx.amount))){existing.add(k); state.transactions.push(tx); added++}}); return added}
function detectCard(text,file){const hay=(text+'\n'+file).replace(/\u200e|\u200f/g,' '); const patterns=[/כרטיס\s+שמסתיים\s+בספרות[:\s]*([0-9]{4})/,/כרטיס\s+שמתסיים\s+בספרות[:\s]*([0-9]{4})/,/כרטיס\s+מאסטרקארד\s+([0-9]{4})/,/קרנות\s+השוטרים\s+([0-9]{4})/,/\*([0-9]{4})\*/,/\b([0-9]{4})\b/]; for(const re of patterns){const m=hay.match(re); if(m)return m[1]} return ''}
function makeTx(date,merchant,amount,card,sourceCategory='',note='',installment=''){return {date:toISO(date),merchant:cleanMerchant(merchant),amount:num(amount),card:card||'',sourceCategory:sourceCategory||'',note,installment:installment||'',exceptional:false,exceptionType:'',source:'pdf'}}
function normalizeText(t){return String(t||'').replace(/\u200e|\u200f/g,' ').replace(/\r/g,'\n').replace(/[\t ]+/g,' ').replace(/\n{2,}/g,'\n')}
function chunkByDate(text){const lines=normalizeText(text).split('\n').map(x=>x.trim()).filter(Boolean); const chunks=[]; let cur=''; const dateStart=/^\d{1,2}[\.\/]\d{1,2}[\.\/]\d{2,4}\b/; for(const line of lines){if(dateStart.test(line)){if(cur)chunks.push(cur.trim()); cur=line}else if(cur){cur+=' '+line}} if(cur)chunks.push(cur.trim()); return chunks}
function moneyMatches(line){return [...String(line).matchAll(/₪\s*(-?[\d,]+(?:\.\d{1,2})?)|-?[\d,]+\.\d{2}/g)].map(m=>(m[1]||m[0]).replace('₪','').trim())}
function installmentOf(line){const m=String(line).match(/תשלום\s*\d+\s*מתוך\s*\d+/); return m?m[0]:''}
const knownCats=['העברת כספים','דלק, חשמל וגז','מכולת/סופר','מסעדות/קפה','נופש ותיור','מוצרי חשמל','תש\' רשויות','שרות רפואי','שירותי רכב','מכוני יופי','בתי ספר','מעדניות','הלבשה','מחשבים','שיווק ישיר','פארמה','ביטוח','תרבות','כלי בית','שונות','דלק'];
function splitByCategory(rest){let best=null,idx=-1; for(const c of knownCats){const i=rest.indexOf(c); if(i>=0&&(idx<0||i<idx)){idx=i;best=c}} if(best)return {merchant:rest.slice(0,idx).trim(),sourceCategory:best,tail:rest.slice(idx+best.length).trim()}; return {merchant:rest.trim(),sourceCategory:'',tail:''}}
function parseMax(text,file,card){const out=[]; for(const ch of chunkByDate(text)){if(/חיוב ב|סה[״"']?כ|המידע המוצג|גרף|אשראי מתגלגל|פירוט החיובים/.test(ch))continue; const d=(ch.match(/^\d{1,2}\.\d{1,2}\.\d{2,4}/)||[])[0]; const monies=moneyMatches(ch); if(!d||!monies.length)continue; const amount=monies[monies.length-1]; let rest=ch.replace(d,' ').replace(/₪\s*-?[\d,]+(?:\.\d{1,2})?/g,' ').replace(/-?[\d,]+\.\d{2}/g,' ').replace(/רגילה|ביטול עסקה|פריקה מיואב/g,' ').replace(/\s+/g,' ').trim(); const installment=installmentOf(ch); rest=rest.replace(/תשלום\s*\d+\s*מתוך\s*\d+/g,' ').trim(); const parts=splitByCategory(rest); let merchant=parts.merchant || rest; if(merchant.length<2)continue; out.push(makeTx(d,merchant,amount,card,parts.sourceCategory,file,installment))} return out}
function parseCal(text,file,card){const lines=normalizeText(text).split('\n').map(x=>x.trim()).filter(Boolean); const out=[]; for(let line of lines){if(/עסקאות לחיוב|פירוט עסקאות|חשבון:|עסקות וחיובים|עמוד|נכון ל-|digital-web|סה"כ/.test(line))continue; const installment=installmentOf(line); let d='', amount='', merchant=''; let m=line.match(/^(\d{1,2}\/\d{1,2}\/\d{2,4})\s+(.+)/); if(m){d=m[1]; const monies=moneyMatches(line); if(!monies.length)continue; amount=monies[monies.length-1]; merchant=m[2].replace(/₪\s*-?[\d,]+(?:\.\d{1,2})?/g,' ').replace(/סכום העסקה\s*-\s*[$€]\s*\d+/g,' ').replace(/תשלום\s*\d+\s*מתוך\s*\d+/g,' ').replace(/[<>‹›]/g,' ').trim()} else {m=line.match(/₪\s*(-?[\d,]+(?:\.\d{1,2})?)\s+(.+?)\s+(\d{1,2}\/\d{1,2}\/\d{2,4})$/); if(m){amount=m[1]; merchant=m[2]; d=m[3]}} if(d&&merchant)out.push(makeTx(d,merchant,amount,card,'',file,installment))} return out}
function parseIsracard(text,file,card){const lines=normalizeText(text).split('\n').map(x=>x.trim()).filter(Boolean); const out=[]; for(let line of lines){if(!/\d{1,2}\/\d{1,2}\/\d{2,4}/.test(line)||!/\d+[,.]\d{2}/.test(line))continue; if(/סה[״"']?כ|מסגרת|ריבית|עמוד|חשבון|פירוט פעולותיך|שער המרה|פ\.עמלה|הנחה|מספר חשבון|רוצה להיות/.test(line))continue; const d=(line.match(/\d{1,2}\/\d{1,2}\/\d{2,4}/)||[])[0]; const nums=[...line.matchAll(/-?[\d,]+\.\d{2}/g)].map(m=>m[0]); if(!d||!nums.length)continue; const foreign=/\$|€|PLN|CHF|WARSZAWA|KRAKOW|PARIS|AMSTERDAM|LUXEMBOURG|SEATTLE|SINGAPORE|KANDERSTEG|BALICE|BRZEZINKA/i.test(line); const amount=foreign?nums[0]:nums[nums.length-1]; const installment=installmentOf(line); let beforeDate=line.slice(0,line.indexOf(d)).trim(); let afterDate=line.slice(line.indexOf(d)+d.length).trim(); let raw=beforeDate.length>3&&!/^\d/.test(beforeDate)?beforeDate:afterDate; raw=raw.replace(/₪\s*-?[\d,]+(?:\.\d{1,2})?/g,' ').replace(/-?[\d,]+\.\d{2}/g,' ').replace(/תש\.נייד|לא הוצג|ה\.קבע|\bא\b/g,' ').replace(/תשלום\s*\d+\s*מתוך\s*\d+/g,' '); const parts=splitByCategory(raw); const merchant=(parts.merchant||raw).trim(); if(merchant.length<2)return; out.push(makeTx(d,merchant,amount,card,parts.sourceCategory||categoryFromLine(line),file,installment))} return out}
function parseGeneric(text,file,card){const rows=normalizeText(text).split('\n').map(x=>x.trim()).filter(Boolean); const out=[]; rows.forEach(line=>{const d=(line.match(/\d{1,2}[\.\/]\d{1,2}[\.\/]\d{2,4}/)||[])[0]; const ms=moneyMatches(line); if(!d||!ms.length)return; let merch=line.replace(d,'').replace(/₪?\s*-?[\d,]+(?:\.\d{1,2})?/g,'').trim(); if(merch.length>2)out.push(makeTx(d,merch,ms.pop(),card,'',file,installmentOf(line)))}); return out}
function cleanMerchant(x){return String(x||'').replace(/\u200e|\u200f/g,' ').replace(/\/ארנק/g,'/ארנק').replace(/\s+/g,' ').replace(/^[\-:·|]+|[\-:·|]+$/g,'').trim()}
async function restoreBackup(e){const f=e.target.files[0]; if(!f)return; state=ensureDefaults(JSON.parse(await f.text())); persist(); e.target.value=''}

function saveCloudConfig(){
  config.email=document.getElementById('cEmail').value.trim().toLowerCase();
  config.password=document.getElementById('cPass').value;
  saveConfig(); log('Settings saved'); render();
}
function initSupabase(){ /* v9: no browser Supabase client. Server function handles cloud. */ }
function log(s){const el=document.getElementById('log'); if(el)el.textContent += new Date().toLocaleTimeString()+' '+s+'\n'}
function requireCloudFields(){
  if(!config.email) throw new Error('חסר אימייל');
  if(!config.password || config.password.length<6) throw new Error('סיסמת Ledger חייבת להיות לפחות 6 תווים');
}
async function callServer(action, payload={}){
  requireCloudFields();
  const res=await fetch('/api/ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email:config.email,password:config.password,...payload})});
  const text=await res.text();
  let json; try{json=JSON.parse(text)}catch{json={ok:false,error:text||('HTTP '+res.status)}}
  if(!res.ok || !json.ok){throw new Error(json.error || json.message || ('HTTP '+res.status))}
  return json;
}
async function testCloud(){
  try{saveCloudConfig(); const r=await callServer('test'); cloudSession=true; log('SERVER TEST OK '+JSON.stringify(r)); alert('בדיקת שרת תקינה. אפשר לטעון/לשמור לענן.');}
  catch(e){cloudSession=false; log('TEST ERROR '+(e.message||e)); alert('שגיאת בדיקה: '+(e.message||e));}
  render();
}
async function signUp(){return testCloud()}
async function signIn(){
  try{saveCloudConfig(); const r=await callServer('load'); cloudSession=true; log('LOGIN/LOAD OK'); if(r.data&&Object.keys(r.data).length){state=ensureDefaults(r.data); localStorage.setItem(LS,JSON.stringify(state));} render(); alert('התחברת ונטען מהענן');}
  catch(e){cloudSession=false; log('LOGIN ERROR '+(e.message||e)); alert('שגיאת כניסה: '+(e.message||e)); render();}
}
async function signOut(){cloudSession=false; render()}
async function loadCloud(){return signIn()}
async function saveCloudNow(){
  try{const payload={...state,lastCloudAt:new Date().toISOString()}; const r=await callServer('save',{data:payload}); cloudSession=true; state.lastCloudAt=new Date().toLocaleString('he-IL'); localStorage.setItem(LS,JSON.stringify(state)); log('Saved cloud'); render(); alert('נשמר בענן');}
  catch(e){log('SAVE ERROR '+(e.message||e)); alert('שגיאת שמירה: '+(e.message||e));}
}
async function cloudSnapshot(){
  try{const r=await callServer('snapshot',{data:state,reason:'manual'}); cloudSession=true; log('Snapshot created'); alert('Snapshot נוצר בענן');}
  catch(e){log('SNAP ERROR '+(e.message||e)); alert('שגיאת Snapshot: '+(e.message||e));}
}
function scheduleCloudSave(){localStorage.setItem(LS,JSON.stringify(state)); if(!cloudSession)return; clearTimeout(saveTimer); saveTimer=setTimeout(()=>saveCloudNow().catch(()=>{}),1500)}
window.addEventListener('load',async()=>{initSupabase(); render()});
render();
